// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhQvpi1DARVA4Txoogb5qVb5-aW13-lwM',
    appId: '1:964131497519:web:6dab4e8b1ca003c44108da',
    messagingSenderId: '964131497519',
    projectId: 'whatever-7b00b',
    authDomain: 'whatever-7b00b.firebaseapp.com',
    storageBucket: 'whatever-7b00b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTl2VWna3lDcHQ7iytgV690sdjVT7kfBc',
    appId: '1:964131497519:android:c905308cac9a3c954108da',
    messagingSenderId: '964131497519',
    projectId: 'whatever-7b00b',
    storageBucket: 'whatever-7b00b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL1U_s9XwILyabflb_4dpLLvuXJbreuCg',
    appId: '1:964131497519:ios:ccfd2a2b73c753c94108da',
    messagingSenderId: '964131497519',
    projectId: 'whatever-7b00b',
    storageBucket: 'whatever-7b00b.appspot.com',
    androidClientId: '964131497519-upggodk0ajl9t81ndpg455hj4fiumnd9.apps.googleusercontent.com',
    iosClientId: '964131497519-vq15uh4iltd9e0daj14quah64dg12h2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatever',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL1U_s9XwILyabflb_4dpLLvuXJbreuCg',
    appId: '1:964131497519:ios:dbf549b6cd4f987d4108da',
    messagingSenderId: '964131497519',
    projectId: 'whatever-7b00b',
    storageBucket: 'whatever-7b00b.appspot.com',
    androidClientId: '964131497519-upggodk0ajl9t81ndpg455hj4fiumnd9.apps.googleusercontent.com',
    iosClientId: '964131497519-gaahnr1kf7gniet07f59nj6h9qrdkvns.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatever.RunnerTests',
  );
}
